package cn.sunn.forensiclion.domain;

// Generated 2013-2-8 23:09:37 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CaseInfor generated by hbm2java
 */
public class CaseInfor implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 37279327124133788L;
	private String caseId;
	private String identifyMajor;
	private Date entrustDate;
	private String identifyRequest;
	private String entrusterAddress;
	private String reportGetway;
	private String receiverName;
	private String receiverAddress;
	private String receiverCode;
	private String receiverEmail;
	private String entruster;
	private String entrusterRelation;
	private String entrusterNum;
	private String linkman;
	private String linkmanTel;
	private String linkmanFax;
	private String identifySender;
	private String insuranceUnit;
	private String insuranceLinkman;
	private String insuranceTel;
	private String insuranceEmail;
	private Date caseDate;
	private String caseClass;
	private Integer caseIdentifyTimes;
	private String caseProgress;
	private String caseRemark;
	private String status;
	private Set<CaseCharge> casecharges = new HashSet<CaseCharge>();
	private Set<CaseIdentifiedInfo> caseidentifiedinfos = new HashSet<CaseIdentifiedInfo>();
	private Set<CaseCheckInfor> casecheckinfors = new HashSet<CaseCheckInfor>();
	private Set<MFile> mfiles = new HashSet<MFile>();
	private CaseInternalStatistics caseinternalstatistics;
	

	public CaseInfor() {
	}

	public CaseInfor(String caseId) {
		this.caseId = caseId;
	}

	public CaseInfor(String caseId, String identifyMajor, Date entrustDate,
			String identifyRequest, String entrusterAddress,
			String reportGetway, String receiverName, String receiverAddress,
			String receiverCode, String receiverEmail, String entruster,
			String entrusterRelation, String entrusterNum, String linkman,
			String linkmanTel, String linkmanFax, String identifySender,
			String insuranceUnit, String insuranceLinkman, String insuranceTel,
			String insuranceEmail, Date caseDate, String caseClass,
			Integer caseIdentifyTimes, String caseProgress, String caseRemark) {
		this.caseId = caseId;
		this.identifyMajor = identifyMajor;
		this.entrustDate = entrustDate;
		this.identifyRequest = identifyRequest;
		this.entrusterAddress = entrusterAddress;
		this.reportGetway = reportGetway;
		this.receiverName = receiverName;
		this.receiverAddress = receiverAddress;
		this.receiverCode = receiverCode;
		this.receiverEmail = receiverEmail;
		this.entruster = entruster;
		this.entrusterRelation = entrusterRelation;
		this.entrusterNum = entrusterNum;
		this.linkman = linkman;
		this.linkmanTel = linkmanTel;
		this.linkmanFax = linkmanFax;
		this.identifySender = identifySender;
		this.insuranceUnit = insuranceUnit;
		this.insuranceLinkman = insuranceLinkman;
		this.insuranceTel = insuranceTel;
		this.insuranceEmail = insuranceEmail;
		this.caseDate = caseDate;
		this.caseClass = caseClass;
		this.caseIdentifyTimes = caseIdentifyTimes;
		this.caseProgress = caseProgress;
		this.caseRemark = caseRemark;
	}

	public String getCaseId() {
		return this.caseId;
	}

	public void setCaseId(String caseId) {
		this.caseId = caseId;
	}

	public String getIdentifyMajor() {
		return this.identifyMajor;
	}

	public void setIdentifyMajor(String identifyMajor) {
		this.identifyMajor = identifyMajor;
	}

	public Date getEntrustDate() {
		return this.entrustDate;
	}

	public void setEntrustDate(Date entrustDate) {
		this.entrustDate = entrustDate;
	}

	public String getIdentifyRequest() {
		return this.identifyRequest;
	}

	public void setIdentifyRequest(String identifyRequest) {
		this.identifyRequest = identifyRequest;
	}

	public String getEntrusterAddress() {
		return this.entrusterAddress;
	}

	public void setEntrusterAddress(String entrusterAddress) {
		this.entrusterAddress = entrusterAddress;
	}

	public String getReportGetway() {
		return this.reportGetway;
	}

	public void setReportGetway(String reportGetway) {
		this.reportGetway = reportGetway;
	}

	public String getReceiverName() {
		return this.receiverName;
	}

	public void setReceiverName(String receiverName) {
		this.receiverName = receiverName;
	}

	public String getReceiverAddress() {
		return this.receiverAddress;
	}

	public void setReceiverAddress(String receiverAddress) {
		this.receiverAddress = receiverAddress;
	}

	public String getReceiverCode() {
		return this.receiverCode;
	}

	public void setReceiverCode(String receiverCode) {
		this.receiverCode = receiverCode;
	}

	public String getReceiverEmail() {
		return this.receiverEmail;
	}

	public void setReceiverEmail(String receiverEmail) {
		this.receiverEmail = receiverEmail;
	}

	public String getEntruster() {
		return this.entruster;
	}

	public void setEntruster(String entruster) {
		this.entruster = entruster;
	}

	public String getEntrusterRelation() {
		return this.entrusterRelation;
	}

	public void setEntrusterRelation(String entrusterRelation) {
		this.entrusterRelation = entrusterRelation;
	}

	public String getEntrusterNum() {
		return this.entrusterNum;
	}

	public void setEntrusterNum(String entrusterNum) {
		this.entrusterNum = entrusterNum;
	}

	public String getLinkman() {
		return this.linkman;
	}

	public void setLinkman(String linkman) {
		this.linkman = linkman;
	}

	public String getLinkmanTel() {
		return this.linkmanTel;
	}

	public void setLinkmanTel(String linkmanTel) {
		this.linkmanTel = linkmanTel;
	}

	public String getLinkmanFax() {
		return this.linkmanFax;
	}

	public void setLinkmanFax(String linkmanFax) {
		this.linkmanFax = linkmanFax;
	}

	public String getIdentifySender() {
		return this.identifySender;
	}

	public void setIdentifySender(String identifySender) {
		this.identifySender = identifySender;
	}

	public String getInsuranceUnit() {
		return this.insuranceUnit;
	}

	public void setInsuranceUnit(String insuranceUnit) {
		this.insuranceUnit = insuranceUnit;
	}

	public String getInsuranceLinkman() {
		return this.insuranceLinkman;
	}

	public void setInsuranceLinkman(String insuranceLinkman) {
		this.insuranceLinkman = insuranceLinkman;
	}

	public String getInsuranceTel() {
		return this.insuranceTel;
	}

	public void setInsuranceTel(String insuranceTel) {
		this.insuranceTel = insuranceTel;
	}

	public String getInsuranceEmail() {
		return this.insuranceEmail;
	}

	public void setInsuranceEmail(String insuranceEmail) {
		this.insuranceEmail = insuranceEmail;
	}

	public Date getCaseDate() {
		return this.caseDate;
	}

	public void setCaseDate(Date caseDate) {
		this.caseDate = caseDate;
	}

	public String getCaseClass() {
		return this.caseClass;
	}

	public void setCaseClass(String caseClass) {
		this.caseClass = caseClass;
	}

	public Integer getCaseIdentifyTimes() {
		return this.caseIdentifyTimes;
	}

	public void setCaseIdentifyTimes(Integer caseIdentifyTimes) {
		this.caseIdentifyTimes = caseIdentifyTimes;
	}

	public String getCaseProgress() {
		return this.caseProgress;
	}

	public void setCaseProgress(String caseProgress) {
		this.caseProgress = caseProgress;
	}

	public String getCaseRemark() {
		return this.caseRemark;
	}

	public void setCaseRemark(String caseRemark) {
		this.caseRemark = caseRemark;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Set<CaseCharge> getCasecharges() {
		return casecharges;
	}

	public void setCasecharges(Set<CaseCharge> casecharges) {
		this.casecharges = casecharges;
	}

	public Set<CaseIdentifiedInfo> getCaseidentifiedinfos() {
		return caseidentifiedinfos;
	}

	public void setCaseidentifiedinfos(Set<CaseIdentifiedInfo> caseidentifiedinfos) {
		this.caseidentifiedinfos = caseidentifiedinfos;
	}

	public Set<CaseCheckInfor> getCasecheckinfors() {
		return casecheckinfors;
	}

	public void setCasecheckinfors(Set<CaseCheckInfor> casecheckinfors) {
		this.casecheckinfors = casecheckinfors;
	}

	public CaseInternalStatistics getCaseinternalstatistics() {
		return caseinternalstatistics;
	}

	public void setCaseinternalstatistics(
			CaseInternalStatistics caseinternalstatistics) {
		this.caseinternalstatistics = caseinternalstatistics;
	}

	public Set<MFile> getMfiles() {
		return mfiles;
	}

	public void setMfiles(Set<MFile> mfiles) {
		this.mfiles = mfiles;
	}

	
}
