package cn.sunn.forensiclion.domain;

// Generated 2013-4-2 9:39:48 by Hibernate Tools 3.4.0.CR1

/**
 * CaseFile generated by hbm2java
 */
public class CaseFile implements java.io.Serializable {

	private Long id;
	private long caseId;
	private long fileId;

	public CaseFile() {
	}

	public CaseFile(long caseId, long fileId) {
		this.caseId = caseId;
		this.fileId = fileId;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public long getCaseId() {
		return this.caseId;
	}

	public void setCaseId(long caseId) {
		this.caseId = caseId;
	}

	public long getFileId() {
		return this.fileId;
	}

	public void setFileId(long fileId) {
		this.fileId = fileId;
	}

}
