package cn.sunn.forensiclion.domain;

// Generated 2013-2-8 9:09:16 by Hibernate Tools 3.4.0.CR1

/**
 * Dictionary generated by hbm2java
 */
public class Dictionary implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5200110547756228724L;
	private long id;
	private long parentid;
	private String name;
	private String code;
	private String content;
	private String remark;

	public Dictionary() {
	}

	public Dictionary(int parentid, String name, String code) {
		this.parentid = parentid;
		this.name = name;
		this.code = code;
	}

	public Dictionary(int parentid, String name, String code, String content,
			String remark) {
		this.parentid = parentid;
		this.name = name;
		this.code = code;
		this.content = content;
		this.remark = remark;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public long getParentid() {
		return this.parentid;
	}

	public void setParentid(long parentid) {
		this.parentid = parentid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
