package cn.sunn.forensiclion.domain;

// Generated 2013-4-2 9:39:48 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * File generated by hbm2java
 */
public class MFile implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6522108318045373212L;
	private Long id;
	private String class_;
	private String filename;
	private byte[] data;
	private Date datetime;

	public MFile() {
	}

	public MFile(String class_, String filename,
			 byte[] data, Date datetime) {
		this.class_ = class_;
		this.filename = filename;
		this.data = data;
		this.datetime = datetime;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getClass_() {
		return this.class_;
	}

	public void setClass_(String class_) {
		this.class_ = class_;
	}

	
	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	

	

	public byte[] getData() {
		return this.data;
	}

	public void setData(byte[] data) {
		this.data = data;
	}

	public Date getDatetime() {
		return this.datetime;
	}

	public void setDatetime(Date datetime) {
		this.datetime = datetime;
	}

}
