package cn.sunn.forensiclion.domain;

// Generated 2013-2-8 9:09:16 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * UsermanageHis generated by hbm2java
 */
public class UsermanageHis implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4152267578409390342L;
	private long id;
	private int userId;
	private Date opdate;
	private String opip;
	private String opcd;
	private String content;

	public UsermanageHis() {
	}

	public UsermanageHis(int id, int userId, Date opdate, String opip,
			String opcd, String content) {
		this.id = id;
		this.userId = userId;
		this.opdate = opdate;
		this.opip = opip;
		this.opcd = opcd;
		this.content = content;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public Date getOpdate() {
		return this.opdate;
	}

	public void setOpdate(Date opdate) {
		this.opdate = opdate;
	}

	public String getOpip() {
		return this.opip;
	}

	public void setOpip(String opip) {
		this.opip = opip;
	}

	public String getOpcd() {
		return this.opcd;
	}

	public void setOpcd(String opcd) {
		this.opcd = opcd;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

}
